### PR TITLE
Scaffolding-update

### PR DESCRIPTION
**Pull request by BurtHarris**
This PR upgrades the build tooling 

Upgrades to those versions used in the latest version of the `yo code` generator.    
Because the eslint settings are more restrictive, I've fixed some obvious warnings.
It also restores the runTest.ts script for testing.   I don't fully understand that, but it seems to work.

### CODE REVIEW

**Comment by BurtHarris** [comment]
Fixes #12

**Comment by BurtHarris** [comment]
I think this is ready

**Comment by BurtHarris** [comment]
Hmm, should the dist directory be listed in .gitignore?
Note, I haven't updated the version number, not sure what protocol you want to follow there.

**Review by BurtHarris — COMMENTED** [review]
Ready now @exceedsystem

**Comment by exceedsystem** [comment]
@BurtHarris

Thank you for your contribution.

I would like to merge your suggestion considering the impact, may take a while as I'm busy these days.

**Review by exceedsystem — CHANGES_REQUESTED** [review]
It has been some time since the pull request was made, but I am finally able to start working on it. 

Could you please make one correction for me?

 The 'dist' directory has been pushed, but the output destination directory should be 'out', so please delete it.

By the way, one reason for not updating the version of the npm libraries is the intention to support older versions of VSCode, so we need to carefully evaluate and decide on updating the library version in the old version of VSCode.

Best regards.

**Pull request closed without merging**
